apiVersion: v1
kind: Service
metadata:
  name: timesheet-service
  namespace: chap4
spec:
  selector:
    app: timesheet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: NodePort
